from pathlib import Path

script = r'''#!/usr/bin/env python3
"""
Phase 6.9a — Freeze 100% 20-Epoch Production Training Streams V1

Purpose
-------
Materialize and freeze the exact full-data training streams for epochs 0..19
BEFORE any production optimizer step.

Each epoch contains:
    1. the shared canonical Phase-5 positive-event order
    2. a deterministic (1,073,249, 4) int32 negative-startup matrix
    3. a deterministic permutation of 5,366,245 serialized examples

Scientific semantics are inherited unchanged from the frozen Phase-5.3.5 V6
generalized stream generator.

This script:
    - instantiates NO neural model
    - instantiates NO Adam optimizer
    - executes NO forward/backward
    - executes 0 optimizer steps
    - executes NO validation
    - accesses/scores NO test cases

Anchors
-------
Epoch 0 must exactly reproduce the frozen Phase-5 epoch-0 stream.
Epoch 1 and epoch 19 must match the frozen Phase-5.3.5 fingerprints.
Epoch 2 additionally regresses against the Phase-6 pre-generation benchmark
performed immediately before this freeze script was created.

The remaining epochs are deterministically generated by the frozen V6
epoch-indexed generator and their fingerprints are frozen here before training.
"""

from __future__ import annotations

import argparse
import gc
import hashlib
import importlib.util
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd


# =============================================================================
# Frozen production dimensions
# =============================================================================

NUM_EPOCHS = 20
POSITIVE_EVENTS = 1_073_249
NEGATIVES_PER_POSITIVE = 4
SLOTS_PER_POSITIVE = 5
EXAMPLES_PER_EPOCH = 5_366_245
BATCH_SIZE = 512
BATCHES_PER_EPOCH = 10_481
FINAL_BATCH_SIZE = 485

EXPECTED_REPOSITORY_HEAD = (
    "6c94a4e787d2bc7a27e9c1ebced3ddf41132d915"
)

EXPECTED_POSITIVE_SHA = (
    "73b074a80675793b811fbdc8a0609883"
    "c857fb2a687a2e01c31865ade5b509d1"
)

EXPECTED_EPOCH0_NEGATIVE_SHA = (
    "47015b147b1949562c0f6737a6f3a3f2"
    "d7cabd2d2202e4e57456d884a1e23fe6"
)

EXPECTED_EPOCH0_ORDER_SHA = (
    "0156be3ee623ade1ae696557337bfb324"
    "e9011adb7df8be9648ecb0a426c134e"
)

EXPECTED_EPOCH1_NEGATIVE_SHA = (
    "f7b415e0f305e049cc94c7e4261b6838"
    "00085f8fa7f7b2df11ff3658dea9d850"
)

EXPECTED_EPOCH1_ORDER_SHA = (
    "2da43d28e540ed48cb557ca889190b5df"
    "ebc7c1207cbd3882df2fa14ca2a28d8"
)

EXPECTED_EPOCH19_NEGATIVE_SHA = (
    "06f9a11d8986ba9b7e0242fc41423478"
    "9ccc7adba91cab6da68ebc21e44682b7"
)

EXPECTED_EPOCH19_ORDER_SHA = (
    "c6236cb081ddba7f72eb0d36199500ac6"
    "b7695646e21a824fb84b85fae769329"
)

# Phase-6 pre-generation benchmark anchor obtained for epoch index 2.
EXPECTED_EPOCH2_NEGATIVE_SHA = (
    "66e2a71c7df08f03d221002541c07611"
    "4a8e6820eae6b42e38988910912e6710"
)

EXPECTED_EPOCH2_ORDER_SHA = (
    "9d5a5e91ad90160ce79b88a0995a8ef7"
    "6ac9cfcd6de00b4cbbfac96fde183474"
)

EXPECTED_ANCHORS = {
    0: {
        "negative_sha256": EXPECTED_EPOCH0_NEGATIVE_SHA,
        "order_sha256": EXPECTED_EPOCH0_ORDER_SHA,
        "anchor_status": "PHASE5_EXACT_FROZEN_REGRESSION",
    },
    1: {
        "negative_sha256": EXPECTED_EPOCH1_NEGATIVE_SHA,
        "order_sha256": EXPECTED_EPOCH1_ORDER_SHA,
        "anchor_status": "PHASE5_DOUBLE_REGENERATION_EXACT",
    },
    2: {
        "negative_sha256": EXPECTED_EPOCH2_NEGATIVE_SHA,
        "order_sha256": EXPECTED_EPOCH2_ORDER_SHA,
        "anchor_status": "PHASE6_PREGENERATION_BENCHMARK_REGRESSION",
    },
    19: {
        "negative_sha256": EXPECTED_EPOCH19_NEGATIVE_SHA,
        "order_sha256": EXPECTED_EPOCH19_ORDER_SHA,
        "anchor_status": "PHASE5_DOUBLE_REGENERATION_EXACT",
    },
}


# =============================================================================
# Frozen source bindings
# =============================================================================

GENERATOR_PATH = Path(
    "scripts/"
    "phase_5_3_5_generalized_20_epoch_training_stream_generator_proof_V6.py"
)

ROUNDTRIP_PATH = Path(
    "scripts/"
    "phase_5_3_2b_checkpoint_resume_roundtrip_proof.py"
)

PHASE5_GENERATOR_CONTRACT_PATH = Path(
    "data/experimental/phase_5/contracts/"
    "phase_5_3_5_generalized_training_stream_generator_contract.json"
)

PHASE5_LAUNCH_CONTRACT_PATH = Path(
    "data/experimental/phase_5/contracts/"
    "phase_5_3_6_production_training_launch_contract.json"
)


# =============================================================================
# Phase-6 full-production outputs
# =============================================================================

OUTPUT_ROOT = Path(
    "data/experimental/phase_6/"
    "full_training/100pct"
)

POSITIVE_OUTPUT_PATH = (
    OUTPUT_ROOT
    / "canonical_training_positive_event_order.parquet"
)

STREAM_DIR = (
    OUTPUT_ROOT
    / "epoch_streams"
)

REGISTRY_PATH = (
    STREAM_DIR
    / "full_epoch_stream_registry.csv"
)

MANIFEST_PATH = (
    STREAM_DIR
    / "full_epoch_stream_manifest.json"
)

CONTRACT_PATH = Path(
    "data/experimental/phase_6/contracts/"
    "phase_6_9a_100pct_20epoch_stream_freeze_V1.json"
)


# =============================================================================
# Helpers
# =============================================================================

def require(condition, message):
    if not bool(condition):
        raise AssertionError(message)


def banner(text):
    print()
    print("=" * 118)
    print(text)
    print("=" * 118)


def load_module(path, name):
    require(
        path.exists(),
        f"Missing source: {path}",
    )

    spec = importlib.util.spec_from_file_location(
        name,
        path,
    )

    require(
        spec is not None
        and spec.loader is not None,
        f"Could not import: {path}",
    )

    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)

    return module


def load_json(path):
    require(
        path.exists(),
        f"Missing JSON contract: {path}",
    )

    with path.open(
        "r",
        encoding="utf-8",
    ) as handle:
        return json.load(handle)


def git_head():
    return (
        subprocess.check_output(
            [
                "git",
                "rev-parse",
                "HEAD",
            ],
            text=True,
        )
        .strip()
    )


def file_sha256(path, chunk_size=8 * 1024 * 1024):
    digest = hashlib.sha256()

    with Path(path).open(
        "rb"
    ) as handle:
        while True:
            chunk = handle.read(
                chunk_size
            )

            if not chunk:
                break

            digest.update(
                chunk
            )

    return digest.hexdigest()


def stable_csv_sha256(frame):
    text = frame.to_csv(
        index=False,
        lineterminator="\n",
    )

    return hashlib.sha256(
        text.encode(
            "utf-8"
        )
    ).hexdigest()


def atomic_numpy_save(array, path):
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary = Path(
        str(path)
        + ".tmp"
    )

    with temporary.open(
        "wb"
    ) as handle:
        np.save(
            handle,
            array,
            allow_pickle=False,
        )

        handle.flush()
        os.fsync(
            handle.fileno()
        )

    os.replace(
        temporary,
        path,
    )


def atomic_csv_write(frame, path):
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary = Path(
        str(path)
        + ".tmp"
    )

    frame.to_csv(
        temporary,
        index=False,
        lineterminator="\n",
    )

    os.replace(
        temporary,
        path,
    )


def atomic_json_write(payload, path):
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary = Path(
        str(path)
        + ".tmp"
    )

    temporary.write_text(
        json.dumps(
            payload,
            indent=2,
            sort_keys=True,
        ),
        encoding="utf-8",
    )

    os.replace(
        temporary,
        path,
    )


def atomic_copy(source, destination):
    destination.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary = Path(
        str(destination)
        + ".tmp"
    )

    shutil.copyfile(
        source,
        temporary,
    )

    os.replace(
        temporary,
        destination,
    )


def metadata_value(metadata, *keys):
    for key in keys:
        if key in metadata:
            value = metadata[
                key
            ]

            if isinstance(
                value,
                np.generic,
            ):
                value = value.item()

            return value

    return None


def epoch_negative_path(epoch):
    return (
        STREAM_DIR
        / (
            f"epoch_{epoch:02d}_"
            "negative_startup_local.npy"
        )
    )


def epoch_order_path(epoch):
    return (
        STREAM_DIR
        / (
            f"epoch_{epoch:02d}_"
            "example_order.npy"
        )
    )


def assert_fresh_targets():
    expected = [
        POSITIVE_OUTPUT_PATH,
        REGISTRY_PATH,
        MANIFEST_PATH,
        CONTRACT_PATH,
    ]

    for epoch in range(
        NUM_EPOCHS
    ):
        expected.append(
            epoch_negative_path(
                epoch
            )
        )

        expected.append(
            epoch_order_path(
                epoch
            )
        )

    existing = [
        str(path)
        for path in expected
        if path.exists()
    ]

    require(
        not existing,
        (
            "Fresh freeze refuses to overwrite existing scientific artifacts:\n"
            + "\n".join(
                existing
            )
        ),
    )


# =============================================================================
# Verification-only mode
# =============================================================================

def verify_existing(
    *,
    preflight,
):
    banner(
        "VERIFY EXISTING FULL 20-EPOCH FREEZE"
    )

    require(
        REGISTRY_PATH.exists(),
        f"Missing registry: {REGISTRY_PATH}",
    )

    require(
        CONTRACT_PATH.exists(),
        f"Missing contract: {CONTRACT_PATH}",
    )

    require(
        POSITIVE_OUTPUT_PATH.exists(),
        f"Missing positive stream: {POSITIVE_OUTPUT_PATH}",
    )

    positive = pd.read_parquet(
        POSITIVE_OUTPUT_PATH
    )

    positive_sha = (
        preflight
        .positive_stream_logical_sha256(
            positive
        )
    )

    require(
        positive_sha
        == EXPECTED_POSITIVE_SHA,
        "Frozen positive-stream fingerprint drift.",
    )

    registry = pd.read_csv(
        REGISTRY_PATH
    )

    require(
        len(
            registry
        )
        == NUM_EPOCHS,
        "Registry does not contain 20 epochs.",
    )

    for epoch in range(
        NUM_EPOCHS
    ):
        row = (
            registry.loc[
                registry[
                    "epoch_index"
                ]
                == epoch
            ]
            .iloc[
                0
            ]
        )

        negative_path = (
            epoch_negative_path(
                epoch
            )
        )

        order_path = (
            epoch_order_path(
                epoch
            )
        )

        require(
            negative_path.exists(),
            f"Missing negative matrix for epoch {epoch}.",
        )

        require(
            order_path.exists(),
            f"Missing order for epoch {epoch}.",
        )

        negative = np.load(
            negative_path,
            mmap_mode="r",
        )

        order = np.load(
            order_path,
            mmap_mode="r",
        )

        negative_sha = (
            preflight
            .array_logical_sha256(
                np.asarray(
                    negative
                )
            )
        )

        order_sha = (
            preflight
            .array_logical_sha256(
                np.asarray(
                    order
                )
            )
        )

        require(
            negative_sha
            == str(
                row[
                    "negative_sha256"
                ]
            ),
            (
                f"Epoch {epoch} negative "
                "fingerprint drift."
            ),
        )

        require(
            order_sha
            == str(
                row[
                    "order_sha256"
                ]
            ),
            (
                f"Epoch {epoch} order "
                "fingerprint drift."
            ),
        )

        require(
            negative.shape
            == (
                POSITIVE_EVENTS,
                NEGATIVES_PER_POSITIVE,
            ),
            (
                f"Epoch {epoch} negative "
                "shape drift."
            ),
        )

        require(
            negative.dtype
            == np.dtype(
                np.int32
            ),
            (
                f"Epoch {epoch} negative "
                "dtype drift."
            ),
        )

        require(
            order.shape
            == (
                EXAMPLES_PER_EPOCH,
            ),
            (
                f"Epoch {epoch} order "
                "shape drift."
            ),
        )

        require(
            order.dtype
            == np.dtype(
                np.int64
            ),
            (
                f"Epoch {epoch} order "
                "dtype drift."
            ),
        )

        print(
            f"epoch={epoch:02d} "
            f"negative={negative_sha[:12]}... "
            f"order={order_sha[:12]}... PASS"
        )

    contract = load_json(
        CONTRACT_PATH
    )

    require(
        contract[
            "status"
        ]
        == "FROZEN_FOR_100PCT_PRODUCTION",
        "Phase-6.9a contract status drift.",
    )

    require(
        contract[
            "registry"
        ][
            "rows"
        ]
        == NUM_EPOCHS,
        "Contract registry-row drift.",
    )

    print()
    print("Positive stream:               PASS")
    print("20 epoch streams:              PASS")
    print("Registry:                      PASS")
    print("Contract:                      PASS")
    print("Optimizer steps executed:      0")
    print("Validation cases scored:       0")
    print("Test cases accessed/scored:    0")
    print()
    print("PHASE 6.9a VERIFY-ONLY: PASS")


# =============================================================================
# Fresh freeze
# =============================================================================

def freeze():
    repository_commit = (
        git_head()
    )

    require(
        repository_commit
        == EXPECTED_REPOSITORY_HEAD,
        (
            "Repository HEAD drift. Expected "
            f"{EXPECTED_REPOSITORY_HEAD}, got "
            f"{repository_commit}."
        ),
    )

    assert_fresh_targets()

    for path in (
        GENERATOR_PATH,
        ROUNDTRIP_PATH,
        PHASE5_GENERATOR_CONTRACT_PATH,
        PHASE5_LAUNCH_CONTRACT_PATH,
    ):
        require(
            path.exists(),
            f"Missing prerequisite: {path}",
        )

    generator_contract = (
        load_json(
            PHASE5_GENERATOR_CONTRACT_PATH
        )
    )

    launch_contract = (
        load_json(
            PHASE5_LAUNCH_CONTRACT_PATH
        )
    )

    require(
        generator_contract[
            "status"
        ]
        == "FROZEN",
        "Phase-5.3.5 generator contract is not FROZEN.",
    )

    require(
        generator_contract[
            "positive_stream"
        ][
            "rows"
        ]
        == POSITIVE_EVENTS,
        "Phase-5 positive count drift.",
    )

    require(
        generator_contract[
            "positive_stream"
        ][
            "logical_sha256"
        ]
        == EXPECTED_POSITIVE_SHA,
        "Phase-5 positive SHA drift.",
    )

    require(
        generator_contract[
            "negative_generator"
        ][
            "K"
        ]
        == NEGATIVES_PER_POSITIVE,
        "Phase-5 K drift.",
    )

    require(
        generator_contract[
            "order_generator"
        ][
            "serialized_examples"
        ]
        == EXAMPLES_PER_EPOCH,
        "Phase-5 serialized-example count drift.",
    )

    require(
        launch_contract[
            "status"
        ]
        == "FROZEN",
        "Phase-5.3.6 launch contract is not FROZEN.",
    )

    schedule = (
        launch_contract[
            "production_schedule"
        ]
    )

    require(
        int(
            schedule[
                "epochs"
            ]
        )
        == NUM_EPOCHS,
        "Launch-contract epoch count drift.",
    )

    require(
        int(
            schedule[
                "examples_per_epoch"
            ]
        )
        == EXAMPLES_PER_EPOCH,
        "Launch-contract example count drift.",
    )

    require(
        int(
            schedule[
                "batches_per_epoch"
            ]
        )
        == BATCHES_PER_EPOCH,
        "Launch-contract batch count drift.",
    )

    require(
        bool(
            launch_contract[
                "test_integrity"
            ][
                "test_forbidden_during_training"
            ]
        ),
        "Frozen launch contract no longer forbids test during training.",
    )

    banner(
        "LOAD FROZEN PHASE-5 STREAM RUNTIME"
    )

    v6 = load_module(
        GENERATOR_PATH,
        "_phase6_9a_generator_v6",
    )

    roundtrip = load_module(
        ROUNDTRIP_PATH,
        "_phase6_9a_roundtrip",
    )

    preflight = (
        roundtrip
        .load_preflight_runtime()
    )

    stream0 = (
        roundtrip
        .load_epoch0_stream(
            preflight
        )
    )

    positive_order = (
        stream0[
            "positive_order"
        ]
    )

    frozen_negative0 = (
        stream0[
            "negative_matrix"
        ]
    )

    frozen_order0 = (
        stream0[
            "epoch_order"
        ]
    )

    require(
        len(
            positive_order
        )
        == POSITIVE_EVENTS,
        "Canonical positive count drift.",
    )

    positive_sha = (
        preflight
        .positive_stream_logical_sha256(
            positive_order
        )
    )

    require(
        positive_sha
        == EXPECTED_POSITIVE_SHA,
        "Canonical positive fingerprint drift.",
    )

    frozen_negative0_sha = (
        preflight
        .array_logical_sha256(
            np.asarray(
                frozen_negative0
            )
        )
    )

    frozen_order0_sha = (
        preflight
        .array_logical_sha256(
            np.asarray(
                frozen_order0
            )
        )
    )

    require(
        frozen_negative0_sha
        == EXPECTED_EPOCH0_NEGATIVE_SHA,
        "Frozen epoch-0 negative fingerprint drift.",
    )

    require(
        frozen_order0_sha
        == EXPECTED_EPOCH0_ORDER_SHA,
        "Frozen epoch-0 order fingerprint drift.",
    )

    required_positive_columns = {
        "interaction_id",
        "investor_global",
        "startup_local",
        "segment_number",
    }

    require(
        required_positive_columns.issubset(
            positive_order.columns
        ),
        "Canonical positive artifact missing required columns.",
    )

    positive_investor = (
        positive_order[
            "investor_global"
        ]
        .to_numpy(
            dtype=np.int64
        )
    )

    positive_startup = (
        positive_order[
            "startup_local"
        ]
        .to_numpy(
            dtype=np.int64
        )
    )

    positive_segment = (
        positive_order[
            "segment_number"
        ]
        .to_numpy(
            dtype=np.int16
        )
    )

    require(
        bool(
            (
                positive_investor
                >= 0
            ).all()
        )
        and bool(
            (
                positive_investor
                < v6.NUM_INVESTORS
            ).all()
        ),
        "Positive investor index outside role universe.",
    )

    require(
        bool(
            (
                positive_startup
                >= 0
            ).all()
        )
        and bool(
            (
                positive_startup
                < v6.NUM_STARTUPS
            ).all()
        ),
        "Positive startup index outside role universe.",
    )

    require(
        bool(
            (
                positive_segment
                >= 1
            ).all()
        )
        and bool(
            (
                positive_segment
                <= 59
            ).all()
        ),
        "Training positive segment outside T1..T59.",
    )

    banner(
        "COPY SHARED CANONICAL POSITIVE STREAM"
    )

    positive_source_path = Path(
        preflight.POSITIVE_ORDER_PATH
    )

    require(
        positive_source_path.exists(),
        f"Missing canonical positive source: {positive_source_path}",
    )

    positive_source_file_sha = (
        file_sha256(
            positive_source_path
        )
    )

    atomic_copy(
        positive_source_path,
        POSITIVE_OUTPUT_PATH,
    )

    require(
        file_sha256(
            POSITIVE_OUTPUT_PATH
        )
        == positive_source_file_sha,
        "Copied positive parquet byte fingerprint drift.",
    )

    copied_positive = pd.read_parquet(
        POSITIVE_OUTPUT_PATH
    )

    copied_positive_sha = (
        preflight
        .positive_stream_logical_sha256(
            copied_positive
        )
    )

    require(
        copied_positive_sha
        == EXPECTED_POSITIVE_SHA,
        "Copied positive logical fingerprint drift.",
    )

    del copied_positive
    gc.collect()

    print(
        f"Source:                         {positive_source_path}"
    )
    print(
        f"Destination:                    {POSITIVE_OUTPUT_PATH}"
    )
    print(
        f"Logical SHA256:                 {copied_positive_sha}"
    )
    print(
        "Byte-exact copy:                 PASS"
    )

    banner(
        "BUILD AUTHORITATIVE PHASE-2 FIRST-POSITIVE INDEX"
    )

    t_pair = time.perf_counter()

    (
        pair_keys_sorted,
        first_segment_sorted,
        pair_index_metadata,
    ) = (
        v6
        .build_first_positive_segment_index_from_phase2(
            temporal_path=(
                v6.TEMPORAL_INTERACTIONS_PATH
            ),
            node_index_path=(
                v6.NODE_INDEX_PATH
            ),
        )
    )

    pair_index_seconds = (
        time.perf_counter()
        - t_pair
    )

    require(
        len(
            pair_keys_sorted
        )
        == len(
            first_segment_sorted
        ),
        "Authoritative pair index length mismatch.",
    )

    print(
        f"Unique pre-T60 pairs:           {len(pair_keys_sorted):,}"
    )
    print(
        f"Pair-index build seconds:       {pair_index_seconds:.3f}"
    )

    banner(
        "20-EPOCH SEED REGISTRY RECHECK"
    )

    seed_rows = []

    for epoch in range(
        NUM_EPOCHS
    ):
        negative_seed = (
            v6
            .derive_epoch_seed(
                v6.NEGATIVE_NAMESPACE,
                epoch,
            )
        )

        order_seed = (
            v6
            .derive_epoch_seed(
                v6.ORDER_NAMESPACE,
                epoch,
            )
        )

        seed_rows.append(
            {
                "epoch_index": epoch,
                "negative_seed": int(
                    negative_seed
                ),
                "order_seed": int(
                    order_seed
                ),
            }
        )

    seed_df = pd.DataFrame(
        seed_rows
    )

    require(
        int(
            seed_df.iloc[
                0
            ][
                "negative_seed"
            ]
        )
        == v6.EXPECTED_EPOCH0_NEGATIVE_SEED,
        "Epoch-0 negative seed drift.",
    )

    require(
        int(
            seed_df.iloc[
                0
            ][
                "order_seed"
            ]
        )
        == v6.EXPECTED_EPOCH0_ORDER_SEED,
        "Epoch-0 order seed drift.",
    )

    require(
        int(
            seed_df.iloc[
                1
            ][
                "negative_seed"
            ]
        )
        == v6.EXPECTED_EPOCH1_NEGATIVE_SEED,
        "Epoch-1 negative seed drift.",
    )

    require(
        int(
            seed_df.iloc[
                1
            ][
                "order_seed"
            ]
        )
        == v6.EXPECTED_EPOCH1_ORDER_SEED,
        "Epoch-1 order seed drift.",
    )

    require(
        int(
            seed_df.iloc[
                19
            ][
                "negative_seed"
            ]
        )
        == v6.EXPECTED_EPOCH19_NEGATIVE_SEED,
        "Epoch-19 negative seed drift.",
    )

    require(
        int(
            seed_df.iloc[
                19
            ][
                "order_seed"
            ]
        )
        == v6.EXPECTED_EPOCH19_ORDER_SEED,
        "Epoch-19 order seed drift.",
    )

    print(
        seed_df.to_string(
            index=False
        )
    )

    banner(
        "MATERIALIZE + FREEZE FULL EPOCH STREAMS"
    )

    STREAM_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    registry_rows = []

    total_generation_start = (
        time.perf_counter()
    )

    selected_traversal = (
        "positive_major_immediate_rejection"
    )

    selected_duplicate_scope = (
        "prior_accepted_within_positive"
    )

    for epoch in range(
        NUM_EPOCHS
    ):
        print()
        print(
            "-" * 118
        )
        print(
            f"EPOCH INDEX {epoch:02d} / 19"
        )
        print(
            "-" * 118
        )

        t_negative = (
            time.perf_counter()
        )

        expected_matrix = (
            np.asarray(
                frozen_negative0
            )
            if epoch == 0
            else None
        )

        (
            negative_matrix,
            metadata,
        ) = (
            v6
            .generate_epoch_negative_matrix(
                epoch_index=epoch,
                positive_investor=(
                    positive_investor
                ),
                positive_segment=(
                    positive_segment
                ),
                pair_keys_sorted=(
                    pair_keys_sorted
                ),
                first_segment_sorted=(
                    first_segment_sorted
                ),
                selected_traversal=(
                    selected_traversal
                ),
                selected_duplicate_scope=(
                    selected_duplicate_scope
                ),
                progress=True,
                expected_matrix=(
                    expected_matrix
                ),
            )
        )

        negative_seconds = (
            time.perf_counter()
            - t_negative
        )

        t_order = (
            time.perf_counter()
        )

        (
            epoch_order,
            order_seed,
        ) = (
            v6
            .generate_epoch_order(
                epoch
            )
        )

        order_seconds = (
            time.perf_counter()
            - t_order
        )

        require(
            negative_matrix.shape
            == (
                POSITIVE_EVENTS,
                NEGATIVES_PER_POSITIVE,
            ),
            f"Epoch {epoch} negative shape drift.",
        )

        require(
            negative_matrix.dtype
            == np.dtype(
                np.int32
            ),
            f"Epoch {epoch} negative dtype drift.",
        )

        require(
            negative_matrix.dtype.str
            == "<i4",
            f"Epoch {epoch} negative dtype.str drift.",
        )

        require(
            bool(
                negative_matrix
                .flags
                .c_contiguous
            ),
            f"Epoch {epoch} negative matrix is not C-contiguous.",
        )

        require(
            epoch_order.shape
            == (
                EXAMPLES_PER_EPOCH,
            ),
            f"Epoch {epoch} order shape drift.",
        )

        require(
            epoch_order.dtype
            == np.dtype(
                np.int64
            ),
            f"Epoch {epoch} order dtype drift.",
        )

        negative_sha = (
            preflight
            .array_logical_sha256(
                negative_matrix
            )
        )

        order_sha = (
            preflight
            .array_logical_sha256(
                epoch_order
            )
        )

        negative_seed = (
            v6
            .derive_epoch_seed(
                v6.NEGATIVE_NAMESPACE,
                epoch,
            )
        )

        require(
            int(
                order_seed
            )
            == int(
                v6
                .derive_epoch_seed(
                    v6.ORDER_NAMESPACE,
                    epoch,
                )
            ),
            f"Epoch {epoch} order seed drift.",
        )

        anchor = (
            EXPECTED_ANCHORS.get(
                epoch
            )
        )

        if anchor is not None:
            require(
                negative_sha
                == anchor[
                    "negative_sha256"
                ],
                (
                    f"Epoch {epoch} negative "
                    "anchor regression failed."
                ),
            )

            require(
                order_sha
                == anchor[
                    "order_sha256"
                ],
                (
                    f"Epoch {epoch} order "
                    "anchor regression failed."
                ),
            )

            anchor_status = (
                anchor[
                    "anchor_status"
                ]
            )

        else:
            anchor_status = (
                "PHASE6_DETERMINISTIC_PRETRAINING_FREEZE"
            )

        if epoch == 0:
            require(
                np.array_equal(
                    negative_matrix,
                    np.asarray(
                        frozen_negative0
                    ),
                ),
                "Epoch-0 negative values differ from frozen Phase-5 artifact.",
            )

            require(
                np.array_equal(
                    epoch_order,
                    np.asarray(
                        frozen_order0
                    ),
                ),
                "Epoch-0 example order differs from frozen Phase-5 artifact.",
            )

        negative_path = (
            epoch_negative_path(
                epoch
            )
        )

        order_path = (
            epoch_order_path(
                epoch
            )
        )

        atomic_numpy_save(
            negative_matrix,
            negative_path,
        )

        atomic_numpy_save(
            epoch_order,
            order_path,
        )

        persisted_negative = (
            np.load(
                negative_path,
                mmap_mode="r",
            )
        )

        persisted_order = (
            np.load(
                order_path,
                mmap_mode="r",
            )
        )

        persisted_negative_sha = (
            preflight
            .array_logical_sha256(
                np.asarray(
                    persisted_negative
                )
            )
        )

        persisted_order_sha = (
            preflight
            .array_logical_sha256(
                np.asarray(
                    persisted_order
                )
            )
        )

        require(
            persisted_negative_sha
            == negative_sha,
            (
                f"Epoch {epoch} persisted negative "
                "fingerprint drift."
            ),
        )

        require(
            persisted_order_sha
            == order_sha,
            (
                f"Epoch {epoch} persisted order "
                "fingerprint drift."
            ),
        )

        repair_positions = (
            metadata_value(
                metadata,
                "repair_positions",
                "repair_rng_draws",
            )
        )

        forbidden_rejections = (
            metadata_value(
                metadata,
                "forbidden_candidate_rejections",
                "forbidden_rejections",
            )
        )

        duplicate_rejections = (
            metadata_value(
                metadata,
                "duplicate_candidate_rejections",
                "duplicate_rejections",
            )
        )

        accepted_future_positive = (
            metadata_value(
                metadata,
                "accepted_future_positive",
            )
        )

        accepted_never_positive = (
            metadata_value(
                metadata,
                "accepted_never_positive",
            )
        )

        registry_rows.append(
            {
                "epoch_index": epoch,
                "negative_seed": int(
                    negative_seed
                ),
                "order_seed": int(
                    order_seed
                ),
                "positive_order_sha256": (
                    EXPECTED_POSITIVE_SHA
                ),
                "negative_sha256": (
                    negative_sha
                ),
                "order_sha256": (
                    order_sha
                ),
                "negative_shape_rows": (
                    POSITIVE_EVENTS
                ),
                "negative_shape_cols": (
                    NEGATIVES_PER_POSITIVE
                ),
                "negative_dtype": (
                    str(
                        negative_matrix.dtype
                    )
                ),
                "negative_dtype_str": (
                    negative_matrix.dtype.str
                ),
                "order_length": (
                    EXAMPLES_PER_EPOCH
                ),
                "order_dtype": (
                    str(
                        epoch_order.dtype
                    )
                ),
                "repair_positions": (
                    repair_positions
                ),
                "forbidden_candidate_rejections": (
                    forbidden_rejections
                ),
                "duplicate_candidate_rejections": (
                    duplicate_rejections
                ),
                "accepted_future_positive": (
                    accepted_future_positive
                ),
                "accepted_never_positive": (
                    accepted_never_positive
                ),
                "negative_generation_seconds": (
                    negative_seconds
                ),
                "order_generation_seconds": (
                    order_seconds
                ),
                "anchor_status": (
                    anchor_status
                ),
                "negative_file": str(
                    negative_path
                ),
                "order_file": str(
                    order_path
                ),
                "negative_file_sha256": (
                    file_sha256(
                        negative_path
                    )
                ),
                "order_file_sha256": (
                    file_sha256(
                        order_path
                    )
                ),
                "generation_status": (
                    "FROZEN_PRETRAINING"
                ),
            }
        )

        print(
            f"negative_seed:                  {negative_seed}"
        )
        print(
            f"order_seed:                     {order_seed}"
        )
        print(
            f"negative_sha256:                {negative_sha}"
        )
        print(
            f"order_sha256:                   {order_sha}"
        )
        print(
            f"negative_generation_seconds:    {negative_seconds:.3f}"
        )
        print(
            f"order_generation_seconds:       {order_seconds:.3f}"
        )
        print(
            f"anchor_status:                  {anchor_status}"
        )
        print(
            "persisted reload verification:  PASS"
        )

        del negative_matrix
        del epoch_order
        del persisted_negative
        del persisted_order
        gc.collect()

    total_generation_seconds = (
        time.perf_counter()
        - total_generation_start
    )

    registry = pd.DataFrame(
        registry_rows
    )

    require(
        len(
            registry
        )
        == NUM_EPOCHS,
        "Final registry does not contain 20 epochs.",
    )

    require(
        registry[
            "negative_sha256"
        ].nunique()
        == NUM_EPOCHS,
        "Expected 20 distinct negative fingerprints.",
    )

    require(
        registry[
            "order_sha256"
        ].nunique()
        == NUM_EPOCHS,
        "Expected 20 distinct order fingerprints.",
    )

    registry_sha = (
        stable_csv_sha256(
            registry
        )
    )

    atomic_csv_write(
        registry,
        REGISTRY_PATH,
    )

    # Re-read and bind the persisted registry bytes/semantics.
    persisted_registry = pd.read_csv(
        REGISTRY_PATH
    )

    require(
        len(
            persisted_registry
        )
        == NUM_EPOCHS,
        "Persisted registry row count drift.",
    )

    require(
        stable_csv_sha256(
            persisted_registry
        )
        == registry_sha,
        "Persisted registry logical CSV fingerprint drift.",
    )

    manifest_files = [
        POSITIVE_OUTPUT_PATH,
        REGISTRY_PATH,
    ]

    for epoch in range(
        NUM_EPOCHS
    ):
        manifest_files.extend(
            [
                epoch_negative_path(
                    epoch
                ),
                epoch_order_path(
                    epoch
                ),
            ]
        )

    manifest = {
        "phase": "6.9a",
        "script_version": "V1",
        "status": "COMPLETE",
        "repository_commit": (
            repository_commit
        ),
        "files": [
            {
                "path": str(
                    path
                ),
                "bytes": int(
                    path.stat().st_size
                ),
                "file_sha256": (
                    file_sha256(
                        path
                    )
                ),
            }
            for path in manifest_files
        ],
    }

    atomic_json_write(
        manifest,
        MANIFEST_PATH,
    )

    contract = {
        "phase": "6.9a",
        "title": (
            "100% 20-Epoch Production Training Stream Freeze"
        ),
        "script_version": "V1",
        "status": (
            "FROZEN_FOR_100PCT_PRODUCTION"
        ),
        "scientific_role": (
            "pre-training materialization of the already-frozen "
            "Phase-5.3.5 generalized epoch-indexed training stream"
        ),
        "repository_commit": (
            repository_commit
        ),
        "sources": {
            "generator": str(
                GENERATOR_PATH
            ),
            "generator_file_sha256": (
                file_sha256(
                    GENERATOR_PATH
                )
            ),
            "roundtrip_runtime": str(
                ROUNDTRIP_PATH
            ),
            "roundtrip_file_sha256": (
                file_sha256(
                    ROUNDTRIP_PATH
                )
            ),
            "phase5_generator_contract": str(
                PHASE5_GENERATOR_CONTRACT_PATH
            ),
            "phase5_launch_contract": str(
                PHASE5_LAUNCH_CONTRACT_PATH
            ),
        },
        "positive_stream": {
            "source_path": str(
                positive_source_path
            ),
            "frozen_copy_path": str(
                POSITIVE_OUTPUT_PATH
            ),
            "rows": (
                POSITIVE_EVENTS
            ),
            "logical_sha256": (
                EXPECTED_POSITIVE_SHA
            ),
            "source_file_sha256": (
                positive_source_file_sha
            ),
            "copy_file_sha256": (
                file_sha256(
                    POSITIVE_OUTPUT_PATH
                )
            ),
            "shared_across_epochs": True,
        },
        "training_stream": {
            "epochs": (
                NUM_EPOCHS
            ),
            "negatives_per_positive": (
                NEGATIVES_PER_POSITIVE
            ),
            "examples_per_epoch": (
                EXAMPLES_PER_EPOCH
            ),
            "batch_size": (
                BATCH_SIZE
            ),
            "batches_per_epoch": (
                BATCHES_PER_EPOCH
            ),
            "final_batch_size": (
                FINAL_BATCH_SIZE
            ),
            "negative_sampling_traversal": (
                selected_traversal
            ),
            "negative_duplicate_scope": (
                selected_duplicate_scope
            ),
            "negative_dtype": "int32",
            "negative_dtype_str": "<i4",
            "order_dtype": "int64",
            "rng": "NumPy PCG64",
            "negative_namespace": (
                v6.NEGATIVE_NAMESPACE
            ),
            "order_namespace": (
                v6.ORDER_NAMESPACE
            ),
            "base_seed": (
                v6.BASE_SEED
            ),
        },
        "frozen_regression_anchors": {
            str(
                epoch
            ): payload
            for epoch, payload
            in EXPECTED_ANCHORS.items()
        },
        "registry": {
            "path": str(
                REGISTRY_PATH
            ),
            "rows": (
                NUM_EPOCHS
            ),
            "stable_csv_sha256": (
                registry_sha
            ),
            "distinct_negative_hashes": int(
                registry[
                    "negative_sha256"
                ].nunique()
            ),
            "distinct_order_hashes": int(
                registry[
                    "order_sha256"
                ].nunique()
            ),
        },
        "generation": {
            "pair_index_seconds": (
                pair_index_seconds
            ),
            "total_epoch_generation_seconds": (
                total_generation_seconds
            ),
            "unique_pre_t60_pairs": int(
                len(
                    pair_keys_sorted
                )
            ),
            "pair_index_metadata": (
                {
                    key: (
                        value.item()
                        if isinstance(
                            value,
                            np.generic,
                        )
                        else value
                    )
                    for key, value
                    in pair_index_metadata.items()
                }
                if isinstance(
                    pair_index_metadata,
                    dict,
                )
                else str(
                    pair_index_metadata
                )
            ),
        },
        "boundary": {
            "model_instantiated": False,
            "optimizer_instantiated": False,
            "forward_backward": False,
            "optimizer_steps": 0,
            "validation_executed": False,
            "validation_cases_scored": 0,
            "test_accessed": False,
            "test_cases_scored": 0,
        },
        "next_phase": {
            "id": "6.9b",
            "title": (
                "100% 20-Epoch CUDA Production Trainer Assembly"
            ),
            "training_allowed_only_after": (
                "phase_6_9a verify-only PASS"
            ),
        },
    }

    atomic_json_write(
        contract,
        CONTRACT_PATH,
    )

    banner(
        "FINAL POST-WRITE VERIFICATION"
    )

    verify_existing(
        preflight=preflight
    )

    banner(
        "PHASE 6.9a FINAL STATUS"
    )

    print(
        "Full positive stream frozen:           PASS"
    )
    print(
        "Full epoch streams frozen:             20 / 20"
    )
    print(
        f"Examples / epoch:                      {EXAMPLES_PER_EPOCH:,}"
    )
    print(
        f"Batches / epoch:                       {BATCHES_PER_EPOCH:,}"
    )
    print(
        f"Final batch size:                      {FINAL_BATCH_SIZE}"
    )
    print(
        "Distinct negative hashes:              20 / 20"
    )
    print(
        "Distinct order hashes:                 20 / 20"
    )
    print(
        f"Total epoch-generation seconds:        {total_generation_seconds:.3f}"
    )
    print(
        "Optimizer steps executed:              0"
    )
    print(
        "Validation cases scored:               0"
    )
    print(
        "Test cases accessed/scored:             0"
    )
    print()
    print(
        f"WROTE  {POSITIVE_OUTPUT_PATH}"
    )
    print(
        f"WROTE  {REGISTRY_PATH}"
    )
    print(
        f"WROTE  {MANIFEST_PATH}"
    )
    print(
        f"WROTE  {CONTRACT_PATH}"
    )
    print()
    print(
        "PHASE 6.9a: COMPLETE / "
        "100% 20-EPOCH STREAMS FROZEN BEFORE TRAINING"
    )


# =============================================================================
# Main
# =============================================================================

def main():
    parser = argparse.ArgumentParser()

    mode = (
        parser
        .add_mutually_exclusive_group(
            required=True
        )
    )

    mode.add_argument(
        "--fresh",
        action="store_true",
        help=(
            "Materialize and freeze all 20 full-data streams. "
            "Refuses to overwrite existing artifacts."
        ),
    )

    mode.add_argument(
        "--verify-only",
        action="store_true",
        help=(
            "Verify an already-frozen Phase-6.9a stream set. "
            "Performs no generation and no training."
        ),
    )

    args = parser.parse_args()

    banner(
        "PHASE 6.9a — "
        "FREEZE 100% 20-EPOCH PRODUCTION TRAINING STREAMS V1"
    )

    print(
        f"Positive events / epoch:               {POSITIVE_EVENTS:,}"
    )
    print(
        f"Negatives / positive:                  {NEGATIVES_PER_POSITIVE}"
    )
    print(
        f"Examples / epoch:                      {EXAMPLES_PER_EPOCH:,}"
    )
    print(
        f"Batches / epoch:                       {BATCHES_PER_EPOCH:,}"
    )
    print(
        f"Final batch size:                      {FINAL_BATCH_SIZE}"
    )
    print(
        f"Epochs:                                {NUM_EPOCHS}"
    )
    print(
        "Model instantiated:                    NO"
    )
    print(
        "Adam instantiated:                     NO"
    )
    print(
        "Optimizer steps:                       0"
    )
    print(
        "Validation:                            DISABLED"
    )
    print(
        "Test:                                  DISABLED"
    )

    if args.fresh:
        freeze()
        return

    # verify-only still requires the frozen runtime for canonical hashing.
    require(
        git_head()
        == EXPECTED_REPOSITORY_HEAD,
        "Repository HEAD drift in verify-only mode.",
    )

    roundtrip = load_module(
        ROUNDTRIP_PATH,
        "_phase6_9a_verify_roundtrip",
    )

    preflight = (
        roundtrip
        .load_preflight_runtime()
    )

    verify_existing(
        preflight=preflight
    )


if __name__ == "__main__":
    main()
'''

out = Path("/mnt/data/phase_6_9a_freeze_100pct_20epoch_streams_V1.py")
out.write_text(script, encoding="utf-8")
print(out)
print(f"{len(script.splitlines())} lines")